name: Carla Client Python Package Build CI

on: 
  workflow_dispatch:
    inputs:
      ubuntu-version:
        description: 'ubuntu version'
        required: true
        default: '20.04'
        type: choice
        options:
        - 20.04
        - 22.04
      carla-version:
        description: 'carla version'
        required: true
        default: '0.9.13'
        type: choice
        options:
        - 0.9.13
        - 0.9.14
        - 0.9.15

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: gezp/ubuntu-desktop:${{github.event.inputs.ubuntu-version}}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential clang lld cmake ninja-build libpng-dev libtiff5-dev libjpeg-dev tzdata sed curl unzip autoconf libtool rsync libxml2-dev
      - name: Download carla github repository
        run: |
          git clone --depth 1 -b ${{github.event.inputs.carla-version}} https://github.com/carla-simulator/carla.git
      - name: Replace build tool with 0.9.14 for 0.9.13
        if: ${{ github.event.inputs.carla-version == '0.9.13' }}
        run: |
          rm -rf carla/Util/BuildTools
          mkdir tmp && cd tmp
          git clone --depth 1 -b 0.9.14 https://github.com/carla-simulator/carla.git 
          cd .. && cp -r tmp/carla/Util/BuildTools carla/Util
      - name : Fix carla/Util/BuildTools/Setup.sh for 0.9.13 and 0.9.14
        run: |
          sed -i 's/git reset --hard ${RECAST_COMMIT}/git checkout carla/g' carla/Util/BuildTools/Setup.sh
          sed -i '/mkdir -p \"${PWD}\/${RECAST_BASENAME}-install\/include\/recast\"/d' carla/Util/BuildTools/Setup.sh
          sed -i '/mv \"${PWD}\/${RECAST_BASENAME}-install\/include\/\"\*h/d' carla/Util/BuildTools/Setup.sh
      - name : Disable test
        run: |
          sed -i 's/add_subdirectory(\"test\")/#add_subdirectory(\"test\")/g' carla/LibCarla/cmake/CMakeLists.txt
      - name : Remove dirty label
        run: |
          sed -i 's/git describe --tags --dirty --always/git describe --tags --always/g' carla/Util/BuildTools/Environment.sh
      - name: Build python package for carla client
        run: |
          cd carla
          make PythonAPI.3
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: carla-${{github.event.inputs.carla-version}}-ubuntu-${{github.event.inputs.ubuntu-version}}
          body: |
            These python packages are built and released by CI for carla client python api.
            Carla: v${{github.event.inputs.carla-version}}
            OS: ubuntu-${{github.event.inputs.ubuntu-version}}
          artifacts: "carla/PythonAPI/carla/dist/*"
